#!/usr/bin/env python3
"""
Overnight build orchestrator for Reel Blocker — ONE FILE PER CALL edition.

Why one file per call:
  A 14B local model can't hold a multi-step scope ("implement steps 10-16") or a
  hard negative constraint across a long tool-call sequence — it overreaches,
  builds the whole project at once, and reintroduces banned syntax. So we shrink
  the unit of work to a SINGLE file per model call, with:
    - a focused per-file spec (pointing at the exact CLAUDE.md section),
    - a SCOPE GUARD that discards anything the model touches outside that one
      file (so overreach becomes harmless),
    - the deterministic verify.sh + behavioral invariants as the gate,
    - files a 14B can't make (PNG icons, the exact YouTube stub) generated by the
      harness with NO model call.

Everything else (preflight, timeouts, escalation, no-op detection, clean-slate
retries, review pass, git tags, auto-resume, run_state/report, circuit breaker)
carries over from the previous design.

Required env:
  export ANTHROPIC_BASE_URL=http://127.0.0.1:1234
  export ANTHROPIC_API_KEY=lm-studio
  export ANTHROPIC_MODEL=qwen3-14b

Optional env:
  RB_RUN_HOURS=0           global wall-clock budget; 0 = no deadline (Ctrl+C stops)
  RB_PRIMARY_TIMEOUT=1200  seconds per primary (one-file) call
  RB_FIX_TIMEOUT=600       seconds per fix call
  RB_REVIEW_TIMEOUT=600    seconds per review call

Usage:
  python3 orchestrator.py                 # run/resume all remaining stages
  python3 orchestrator.py --dry-run       # list the stages and prompts
  python3 orchestrator.py --from-stage=12 # pin start (overrides tag auto-resume)
  python3 orchestrator.py --no-review     # skip the (already optional) review pass
  python3 orchestrator.py --skip-preflight

Resume: with no --from-stage, the run auto-resumes after the highest verified
`stage-N` git tag. Per-call timeouts always apply, so a hung call can't stall the
run even with no global deadline.
"""
import os, re, sys, json, time, struct, zlib, hashlib, pathlib, shutil, subprocess, datetime
import urllib.request

REPO = pathlib.Path(__file__).resolve().parent


class AbortRun(Exception):
    """Raised to stop the run cleanly (e.g. model server appears down)."""


# --- tunables (sized for single-file units) -------------------------------
MAX_TURNS         = "60"   # one file shouldn't need 200 turns
MAX_FIX_TURNS     = "40"
MAX_REVIEW_TURNS  = "30"
MAX_FIX_ROUNDS    = 4
MAX_REVIEW_ROUNDS = 2
MAX_STAGE_ATTEMPTS = 2
DIFF_BUDGET       = 12000
FILE_BUDGET       = 10000

def _int_env(name, default):
    try: return int(os.environ.get(name, default))
    except ValueError: return default

RUN_HOURS       = float(os.environ.get("RB_RUN_HOURS", "0"))
PRIMARY_TIMEOUT = _int_env("RB_PRIMARY_TIMEOUT", 1200)
FIX_TIMEOUT     = _int_env("RB_FIX_TIMEOUT", 600)
REVIEW_TIMEOUT  = _int_env("RB_REVIEW_TIMEOUT", 600)

FAST_FAIL_SECONDS = 30
MAX_CONSEC_FAST_FAILS = 4
_health = {"consec_fast_fail": 0}


# --- the build, one file per stage ---------------------------------------
# Order is dependency-safe: shared libs first; icons before manifests; manifests
# LAST so every file they reference already exists (verify checks the refs).
# `scripted` stages are generated by the harness with no model call.
FILES = [
    dict(file="lib/browser-polyfill.js", desc="namespace shim",
         spec="A tiny shim so all other code can use `browser.*`. Set a global that "
              "points to the existing `browser` if defined, otherwise `chrome`. It "
              "must work in BOTH content scripts and the MV3 service worker (no "
              "window), so use globalThis, e.g. "
              "`globalThis.browser = globalThis.browser || globalThis.chrome;`. "
              "Nothing else. No import/require/export."),

    dict(file="content/shared/storage.js", desc="storage wrapper + defaults",
         review="storage.js wraps every browser.storage call in try/catch, falls "
                "back to defaults blockingEnabled=true / allowFollowing=false, never "
                "throws; all functions hang off window.RB; no module syntax.",
         spec="window.RB = window.RB || {}; then add: RB.getSettings(cb) reading "
              "browser.storage.sync with defaults {blockingEnabled:true, "
              "allowFollowing:false}; RB.setSettings(obj,cb); RB.getLocal(cb) reading "
              "browser.storage.local {blockingStartTime, pausedElapsed}; "
              "RB.setLocal(obj,cb). Wrap EVERY storage call in try/catch and on any "
              "error call back with the defaults — never throw (CLAUDE.md 'Storage "
              "Schema' + 'Error Handling'). No import/require/export."),

    dict(file="content/shared/blocker.js", desc="block / placeholder / unblock",
         spec="window.RB functions copied EXACTLY from CLAUDE.md 'DOM Manipulation': "
              "RB.blockElement(el) (idempotent via el.dataset.rbBlocked, sets "
              "display:none); RB.placeholderElement(el,text) (replaces innerHTML with "
              "the styled placeholder shown in the spec); RB.unblockAll() (restores "
              "every [data-rb-blocked] element). No import/require/export."),

    dict(file="content/shared/observer.js", desc="debounced MutationObserver factory",
         spec="window.RB.createObserver(scanFn): a MutationObserver with a 50ms "
              "debounce (CLAUDE.md 'MutationObserver'), observing document.body with "
              "{childList:true, subtree:true}; run scanFn() once immediately and "
              "return the observer. Wrap scanFn in try/catch + console.error. No "
              "import/require/export."),

    dict(file="assets/icons", scripted="icons", desc="placeholder PNG icons (scripted)",
         expects=["assets/icons/icon16.png", "assets/icons/icon32.png",
                  "assets/icons/icon48.png", "assets/icons/icon128.png",
                  "assets/icons/icon-16.png", "assets/icons/icon-32.png",
                  "assets/icons/icon-48.png", "assets/icons/icon-128.png"]),

    dict(file="popup/popup.html", desc="popup markup",
         spec="Build the popup from CLAUDE.md 'Popup UI' layout: title 'Reel "
              "Blocker'; a prominent timer area with separate elements (ids #days "
              "#hrs #min); a divider; the master toggle 'Block short-form content'; "
              "a divider; the sub-toggle 'Allow from people I follow'. Link "
              "popup.css and popup.js. EXACTLY one master toggle and one sub-toggle "
              "— no per-platform toggles."),

    dict(file="popup/popup.css", desc="popup styling",
         spec="Dark theme per CLAUDE.md 'Popup UI': background #111, white text, "
              "fixed 280px width, minimal. Timer is the visual hero (large). Style "
              "the two toggles as switches."),

    dict(file="popup/popup.js", desc="popup logic + timer",
         review="popup.js reads/writes both toggles via the RB storage helpers and "
                "computes elapsed from blockingStartTime / pausedElapsed exactly per "
                "the Timer rules (reset on ON, freeze on OFF); no module syntax; no "
                "localStorage.",
         spec="On load: read settings + local state via the RB storage helpers, "
              "reflect both toggle positions, render the timer. Timer math MUST "
              "match CLAUDE.md 'Timer'/lib/timer.js: elapsed = now - "
              "blockingStartTime when ON, else pausedElapsed; split into "
              "days/hrs/min. On master toggle change: ON sets blockingStartTime=now "
              "and pausedElapsed=0; OFF freezes pausedElapsed = now - "
              "blockingStartTime. Persist toggles to storage.sync, timer fields to "
              "storage.local. Use the names blockingStartTime / pausedElapsed. Do "
              "NOT use localStorage. No import/require/export."),

    dict(file="background/service-worker.js", desc="MV3 dynamic redirect rules",
         review="service-worker.js uses chrome.declarativeNetRequest."
                "updateDynamicRules (NOT static rules), adds ALL Instagram+TikTok "
                "redirect rules when blockingEnabled turns ON and removes them all "
                "when OFF, listens to storage.onChanged, and uses self/globalThis "
                "not window.",
         spec="MV3 service worker. Use chrome.declarativeNetRequest.updateDynamicRules "
              "ONLY (CLAUDE.md 'Dynamic Rule Management'). Rules: Instagram ids "
              "100-109 redirecting /reels/ and /reel/* to "
              "https://www.instagram.com/?variant=following ; TikTok ids 200-209 "
              "redirecting /video/* to https://www.tiktok.com/following . On worker "
              "startup AND on browser.storage.onChanged for blockingEnabled: ON adds "
              "every rule, OFF removes every rule by id. NEVER reference window — use "
              "self/globalThis. No import/require/export."),

    dict(file="background/background.firefox.js", desc="MV2 webNavigation redirect",
         spec="Firefox MV2 background. Use browser.webNavigation.onBeforeNavigate to "
              "redirect the same URLs as the MV3 worker (Instagram /reels/ and "
              "/reel/* -> /?variant=following ; TikTok /video/* -> /following) but "
              "ONLY when blockingEnabled is true (read via browser.storage). Use "
              "browser.tabs.update to redirect. No import/require/export."),

    dict(file="content/instagram/nav.js", desc="remove Reels nav icon",
         spec="window.RB Instagram nav module. Expose a scan function (e.g. "
              "window.RB.igNavScan) that hides the Reels nav entry: match "
              "a[href='/reels/'] and nav a[aria-label*='Reels' i] (CLAUDE.md 'Known "
              "Selector Starting Points') and hide the whole nav item via "
              "RB.blockElement. No import/require/export."),

    dict(file="content/instagram/redirect.js", desc="/reels/ + SPA pushState",
         review="redirect.js redirects /reels/, /reel/XXXX/ and /audio/* to the "
                "following feed AND monkey-patches history.pushState plus listens to "
                "popstate (CLAUDE.md 'SPA Navigation Interception').",
         spec="window.RB Instagram redirect module. checkAndRedirect(): if pathname "
              "is /reels/ or matches /reel/<id>/ or starts with /audio/, set "
              "location to https://www.instagram.com/?variant=following . "
              "Monkey-patch history.pushState (original then checkAndRedirect), add "
              "a popstate listener, and call checkAndRedirect() once on load — "
              "EXACTLY the pattern in CLAUDE.md 'SPA Navigation Interception'. No "
              "import/require/export."),

    dict(file="content/instagram/feed.js", desc="For You->Following + block reels",
         review="feed.js auto-redirects For You to Following (variant=following) and "
                "hides whole reel cards via RB.blockElement, but SKIPS blocking in "
                "the Following tab when allowFollowing is on; never touches Stories, "
                "photo posts or carousels.",
         spec="window.RB Instagram feed module. On the home feed auto-redirect the "
              "For You tab to Following (append ?variant=following). Scan reel cards "
              "(article:has(video)) but EXCLUDE anything under an ancestor whose "
              "aria-label contains 'Stories'; hide the WHOLE card via RB.blockElement. "
              "If allowFollowing is on AND url has variant=following, do NOT block "
              "those reels. Read toggles via RB.getSettings. Must not affect photo "
              "posts or Stories (CLAUDE.md 'Instagram — Surfaces'). No "
              "import/require/export."),

    dict(file="content/instagram/explore.js", desc="block explore reels, keep photos",
         spec="window.RB Instagram explore module. On /explore/, hide cards "
              "containing <video> via RB.blockElement while leaving photo posts "
              "visible (CLAUDE.md 'Explore page'). No import/require/export."),

    dict(file="content/instagram/profile.js", desc="hide Reels tab, redirect /reels/",
         spec="window.RB Instagram profile module. On profile pages hide the Reels "
              "tab (a[href$='/reels/']) via RB.blockElement; if the path ends in "
              "/reels/ redirect to the profile root (CLAUDE.md 'Profile page'). Do "
              "not touch the photo grid. No import/require/export."),

    dict(file="content/instagram/dms.js", desc="reel DM placeholder",
         review="dms.js replaces reel preview cards in DMs with a placeholder via "
                "RB.placeholderElement (must NOT remove them; must NOT break the "
                "thread, composer, or other messages).",
         spec="window.RB Instagram DM module. In a DM thread, find reel preview "
              "cards and replace them via RB.placeholderElement(el,'Reel blocked') — "
              "do NOT hide or remove (CLAUDE.md 'DMs — reel preview card'). Must "
              "never break messaging or non-reel messages. No import/require/export."),

    dict(file="content/instagram/instagram.js", desc="Instagram entry point",
         review="instagram.js reads blockingEnabled first (if off -> RB.unblockAll "
                "and stop), wires the nav/feed/explore/profile/dms scans through "
                "RB.createObserver with per-scan try/catch, starts redirect, and "
                "re-runs on storage.onChanged.",
         spec="window.RB Instagram entry point. scanAndBlock() calls the IG "
              "nav/feed/explore/profile/dms scan functions, each guarded by "
              "try/catch; wire it via RB.createObserver(scanAndBlock). Read "
              "blockingEnabled first; if OFF call RB.unblockAll() and do nothing "
              "else. Re-run on browser.storage.onChanged. No import/require/export."),

    dict(file="content/tiktok/redirect.js", desc="/video/ + SPA pushState",
         review="tiktok/redirect.js handles /video/* and patches history.pushState + "
                "popstate (CLAUDE.md 'SPA Navigation Interception').",
         spec="window.RB TikTok redirect module. checkAndRedirect(): if pathname "
              "starts with /video/, redirect to https://www.tiktok.com/following "
              "(following.js renders the blocked screen there when allowFollowing is "
              "off). Monkey-patch history.pushState (original then checkAndRedirect), "
              "add popstate listener, call once on load. No import/require/export."),

    dict(file="content/tiktok/feed.js", desc="For You/Explore blocked-screen overlay",
         review="tiktok/feed.js renders the full blocked-screen overlay from the "
                "spec (dark #0a0a0a, 'Short-form content blocked', subtext 'Focus "
                "Guard is active', no buttons, covering the whole feed) on For You "
                "and Explore.",
         spec="window.RB TikTok feed module. On For You (/ or /foryou) and Explore, "
              "replace/cover the feed with the blocked-screen overlay EXACTLY per "
              "CLAUDE.md 'TikTok Blocked Screen Design': dark background #0a0a0a, "
              "centred white text 'Short-form content blocked', smaller subtext "
              "'Focus Guard is active', no buttons, covering the entire feed so no "
              "video shows underneath. No import/require/export."),

    dict(file="content/tiktok/following.js", desc="Following feed conditional",
         review="tiktok/following.js shows the Following feed only when "
                "allowFollowing is on; otherwise the blocked screen.",
         spec="window.RB TikTok following module. On /following: if allowFollowing "
              "is on, leave the feed visible; otherwise show the same blocked-screen "
              "overlay as feed.js (CLAUDE.md 'Following feed'). Read the toggle via "
              "RB.getSettings. No import/require/export."),

    dict(file="content/tiktok/nav.js", desc="hide For You / Explore nav items",
         spec="window.RB TikTok nav module. Hide the For You and Explore nav items "
              "via RB.blockElement (CLAUDE.md TikTok surfaces). No "
              "import/require/export."),

    dict(file="content/tiktok/dms.js", desc="TikTok video DM placeholder",
         review="tiktok/dms.js replaces video previews in the inbox with a "
                "placeholder and never breaks the inbox/messaging.",
         spec="window.RB TikTok DM module. In the inbox, replace video previews via "
              "RB.placeholderElement(el,'TikTok video blocked'). Must never break "
              "the inbox or messaging (CLAUDE.md 'DMs with video previews'). No "
              "import/require/export."),

    dict(file="content/tiktok/tiktok.js", desc="TikTok entry point",
         review="tiktok.js reads blockingEnabled first (off -> RB.unblockAll + "
                "stop), wires feed/following/nav/dms scans via RB.createObserver "
                "with try/catch, starts redirect, re-runs on storage.onChanged.",
         spec="window.RB TikTok entry point. scanAndBlock() calls the TikTok "
              "feed/following/nav/dms scan functions, each guarded by try/catch; "
              "wire via RB.createObserver(scanAndBlock). Read blockingEnabled first; "
              "if OFF call RB.unblockAll() and stop. Re-run on storage.onChanged. No "
              "import/require/export."),

    dict(file="content/youtube/youtube.js", scripted="youtube",
         desc="Phase 2 stub (scripted, exact comment)"),

    dict(file="manifest.json", desc="Chromium MV3 manifest",
         review="manifest.json (MV3) requests ONLY storage, declarativeNetRequest, "
                "webNavigation + the three host_permissions; lists the content "
                "scripts in load order; sets the service worker, popup and icons; "
                "all referenced files exist.",
         spec="Chromium MV3 manifest per CLAUDE.md 'Manifest Permissions'. "
              "permissions: storage, declarativeNetRequest, webNavigation. "
              "host_permissions: the three sites. For Instagram and TikTok, a "
              "content_scripts entry (run_at document_idle) loading IN THIS ORDER: "
              "lib/browser-polyfill.js, content/shared/storage.js, "
              "content/shared/blocker.js, content/shared/observer.js, then that "
              "platform's modules, then its entry point (instagram.js / tiktok.js). "
              "Add a YouTube entry loading the stub. background.service_worker = "
              "background/service-worker.js. action.default_popup = popup/popup.html. "
              "icons 16/32/48/128 from assets/icons. Request NOTHING else."),

    dict(file="manifest.firefox.json", desc="Firefox MV2 manifest",
         review="manifest.firefox.json (MV2) requests only the permitted "
                "permissions + host perms; background.scripts loads the polyfill + "
                "background.firefox.js; same content scripts; browser_action popup; "
                "icons exist.",
         spec="Firefox MV2 manifest per CLAUDE.md. manifest_version 2. permissions: "
              "storage, webNavigation, and the three host match patterns. "
              "background.scripts = [lib/browser-polyfill.js, "
              "background/background.firefox.js]. Same content_scripts as "
              "manifest.json (same load order). browser_action.default_popup = "
              "popup/popup.html. icons 16/32/48/128. Request NOTHING else."),

    dict(file="AGENT_SUMMARY.md", desc="final summary",
         spec="Write AGENT_SUMMARY.md per CLAUDE.md 'When All Steps Are Complete': "
              "which files were built, any '// AGENT STOP:' comments (search the "
              "repo) reproduced with context, anything needing manual testing before "
              "use, and any selector that could not be verified against a live DOM. "
              "This is the only file to create this stage."),
]

# --- prompts --------------------------------------------------------------
STYLE = """\
HARD RULES — read these first, check them again before finishing:

RULE 1 — NO MODULE SYNTAX IN content/ OR background/.
require, import, export, module.exports, exports. must NOT appear in any file
under content/ or background/. They do not exist in content scripts or MV3
service workers; the extension silently fails to load. Share everything through
the window.RB.* namespace instead. WRONG: `export { a, b };`, `export default
{}`, `export function f(){}`, `import x from './y'`, `const x=require('./y')`,
`module.exports=...`. CORRECT: `window.RB = window.RB || {}; window.RB.f =
function(){...};` and just call `window.RB.f()` from other files.

RULE 2 — background/service-worker.js: NO window. Use self or globalThis.
RULE 3 — Do NOT invent classes. Share everything through window.RB.* functions.
RULE 4 — Vanilla JS only. No npm, no frameworks, no localStorage.
"""

ONE_FILE_PROMPT = """\
Read CLAUDE.md in full FIRST — it is the complete spec.

This stage creates EXACTLY ONE file:  {file}

Do NOT create, edit, rename or delete any other file, and do NOT run any git
command — the harness commits for you. Anything you touch outside {file} is
discarded automatically, so put all your effort into making {file} correct,
complete and self-contained.

Spec for {file}:
{spec}

When done, run scripts/verify.sh and make sure it reports no problem for {file}.
"""

FIX_PROMPT = """\
scripts/verify.sh (and/or the completeness check) failed for {file}. You may ONLY
edit {file} — nothing else. Errors:

{errors}
{escalation}
Fix every failure. Re-read RULE 1 (no import/export/require/module.exports). Then
run scripts/verify.sh again and confirm it reports no problem for {file}.
"""

REVIEW_FIX_PROMPT = """\
A review of {file} found spec violations the automated gate can't see. You may
ONLY edit {file}. Fix each, keep RULE 1, then re-run scripts/verify.sh.

Findings:
{findings}
"""

REVIEW_PROMPT = """\
REVIEW ONLY. Do NOT edit any file. Read CLAUDE.md (the spec), then audit the diff
of {file} below.

Check ONLY:
{checklist}

If every item holds, respond with exactly this on its own line:
REVIEW: PASS
Otherwise:
REVIEW: FAIL
then a short numbered list of concrete problems to fix in {file}.

--- GIT DIFF ({file}) ---
{diff}
"""


# --- deterministic post-processor ----------------------------------------
def strip_module_syntax(repo):
    """Fix the module-syntax mistakes a 14B makes repeatedly, so we don't spend a
    model call on what a regex handles for free. Now also covers the block forms
    `export { ... };` and `export default ...` that slipped through before."""
    changed = []
    for d in (repo / "content", repo / "background"):
        if not d.exists():
            continue
        for f in d.rglob("*.js"):
            text = original = f.read_text(encoding="utf-8")
            text = re.sub(r"^import\s+[\w{},\s*]+\s+from\s+['\"].*?['\"];?\s*$", "",
                          text, flags=re.MULTILINE)
            text = re.sub(r"^(?:const|let|var)\s+\w+\s*=\s*require\s*\([^)]+\);?\s*$", "",
                          text, flags=re.MULTILINE)
            # named-export block:  export { a, b, c };  -> drop entirely
            text = re.sub(r"^export\s*\{[^}]*\}\s*;?\s*$", "", text, flags=re.MULTILINE)
            # export default <expr>;  -> drop the `export default ` lead-in
            text = re.sub(r"^export\s+default\s+", "", text, flags=re.MULTILINE)
            # module.exports = ...;   -> drop
            text = re.sub(r"^\s*module\.exports\s*=.*$", "", text, flags=re.MULTILINE)
            text = re.sub(r"^export\s+function\s+(\w+)\s*\(",
                          r"window.RB.\1 = function(", text, flags=re.MULTILINE)
            text = re.sub(r"^export\s+(?:const|let|var)\s+(\w+)\s*=",
                          r"window.RB.\1 =", text, flags=re.MULTILINE)
            if text != original:
                f.write_text(text, encoding="utf-8")
                changed.append(str(f.relative_to(repo)))
    if changed:
        print(f"  [post-process] fixed module syntax in: {', '.join(changed)}")


# --- git helpers ----------------------------------------------------------
def git(repo, *args, check=False, capture=False):
    return subprocess.run(["git", *args], cwd=repo, check=check, text=True,
                          stdout=subprocess.PIPE if capture else None,
                          stderr=subprocess.STDOUT if capture else None)

def head(repo):
    return (git(repo, "rev-parse", "HEAD", capture=True).stdout or "").strip()

def reset_clean(repo, ref):
    git(repo, "reset", "--hard", ref)
    git(repo, "clean", "-fd")

def in_baseline(repo, baseline, path):
    r = subprocess.run(["git", "cat-file", "-e", f"{baseline}:{path}"], cwd=repo,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return r.returncode == 0

def scope_guard(repo, baseline, allowed):
    """The core of one-file-per-call: after a model call, neutralise any model
    commits and discard EVERY change outside the allowed file set, so the model
    physically cannot affect other files. Leaves working tree = baseline + allowed
    changes."""
    allowed = set(allowed)
    git(repo, "reset", "--mixed", baseline)  # undo model commits, keep worktree
    r = git(repo, "status", "--porcelain", capture=True)
    reverted = []
    for line in (r.stdout or "").splitlines():
        path = line[3:]
        if " -> " in path:           # rename: keep the destination path
            path = path.split(" -> ", 1)[1]
        path = path.strip().strip('"')
        if not path or path in allowed:
            continue
        if in_baseline(repo, baseline, path):
            git(repo, "checkout", baseline, "--", path)
        else:
            try: (repo / path).unlink()
            except OSError: pass
        reverted.append(path)
    if reverted:
        uniq = sorted(set(reverted))
        print(f"  [scope] discarded out-of-scope changes: {', '.join(uniq[:8])}"
              + (" ..." if len(uniq) > 8 else ""))
    return reverted

def worktree_signature(repo, baseline):
    git(repo, "add", "-A")
    r = git(repo, "diff", "--cached", baseline, capture=True)
    sig = hashlib.sha1((r.stdout or "").encode("utf-8", "replace")).hexdigest()
    git(repo, "reset", "-q")
    return sig

def stage_diff(repo, baseline, budget=DIFF_BUDGET):
    git(repo, "add", "-A")
    r = git(repo, "diff", "--cached", baseline, capture=True)
    git(repo, "reset", "-q")
    d = r.stdout or ""
    return d if len(d) <= budget else d[:budget] + f"\n... [diff truncated] ..."

def highest_stage_tag(repo):
    r = git(repo, "tag", "--list", "stage-*", capture=True)
    best = 0
    for line in (r.stdout or "").splitlines():
        m = re.match(r"stage-(\d+)$", line.strip())
        if m: best = max(best, int(m.group(1)))
    return best


# --- scripted file generators (no model call) ----------------------------
def _write_png(path, n, rgb=(17, 17, 17)):
    """Minimal valid solid-colour RGB PNG, dependency-free."""
    def chunk(typ, data):
        return (struct.pack(">I", len(data)) + typ + data +
                struct.pack(">I", zlib.crc32(typ + data) & 0xffffffff))
    ihdr = struct.pack(">IIBBBBB", n, n, 8, 2, 0, 0, 0)  # 8-bit truecolour
    row = b"\x00" + bytes(rgb) * n
    idat = zlib.compress(row * n, 9)
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) +
           chunk(b"IDAT", idat) + chunk(b"IEND", b""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)

YOUTUBE_STUB = (
    "// Phase 2 — YouTube Shorts blocker\n"
    "// Not yet implemented. See CLAUDE.md for surface list when ready.\n"
    "// Surfaces: Shorts shelf on homepage, Shorts nav tab,\n"
    "// /shorts/XXXX URLs, Shorts in search results, Shorts on channel pages.\n"
)

def run_scripted(repo, kind):
    if kind == "icons":
        # Emit BOTH naming conventions (icon16.png AND icon-16.png) so the
        # manifest stage passes regardless of which form the model writes.
        # Cheap insurance for an unattended run — 8 tiny PNGs instead of 4.
        for sz in (16, 32, 48, 128):
            _write_png(repo / "assets" / "icons" / f"icon{sz}.png", sz)
            _write_png(repo / "assets" / "icons" / f"icon-{sz}.png", sz)
        print("  [scripted] generated assets/icons/icon{,-}{16,32,48,128}.png")
    elif kind == "youtube":
        p = repo / "content" / "youtube" / "youtube.js"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(YOUTUBE_STUB, encoding="utf-8")
        print("  [scripted] wrote content/youtube/youtube.js stub")
    else:
        raise AbortRun(f"unknown scripted kind: {kind}")


# --- claude CLI -----------------------------------------------------------
def claude_cmd(prompt, max_turns):
    return ["claude", "-p", prompt, "--dangerously-skip-permissions",
            "--max-turns", max_turns]

def _note_call(ok, duration, timed_out):
    if ok or timed_out or duration >= FAST_FAIL_SECONDS:
        _health["consec_fast_fail"] = 0
    else:
        _health["consec_fast_fail"] += 1
    if _health["consec_fast_fail"] >= MAX_CONSEC_FAST_FAILS:
        raise AbortRun(f"{MAX_CONSEC_FAST_FAILS} consecutive fast model-call "
                       f"failures — is the server up at "
                       f"{os.environ.get('ANTHROPIC_BASE_URL','?')}? Aborting.")

def run_claude(prompt, max_turns, log, timeout, capture=False):
    t0 = time.time()
    try:
        if capture:
            r = subprocess.run(claude_cmd(prompt, max_turns), cwd=REPO, text=True,
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               timeout=timeout)
            if log: log.write(r.stdout or ""); log.flush()
            _note_call(r.returncode == 0, time.time() - t0, False)
            return r.returncode == 0, (r.stdout or "")
        r = subprocess.run(claude_cmd(prompt, max_turns), cwd=REPO,
                           stdout=log, stderr=subprocess.STDOUT, timeout=timeout)
        _note_call(r.returncode == 0, time.time() - t0, False)
        return r.returncode == 0, None
    except subprocess.TimeoutExpired:
        msg = f"\n  [timeout] claude call exceeded {timeout}s — abandoning.\n"
        print(msg, end="")
        if log: log.write(msg); log.flush()
        _note_call(False, time.time() - t0, True)
        return False, None


# --- gates ----------------------------------------------------------------
def run_verify(repo):
    r = subprocess.run(["./scripts/verify.sh"], cwd=repo, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return r.returncode == 0, r.stdout

def completeness(repo, expects):
    problems = []
    for rel in expects:
        p = repo / rel
        if not p.exists():
            problems.append(f"MISSING FILE: {rel}")
        elif p.stat().st_size < 30:
            problems.append(f"STUB/EMPTY FILE: {rel} ({p.stat().st_size} bytes)")
    return (len(problems) == 0, "\n".join(problems))

REVIEW_VERDICT = re.compile(r"REVIEW:\s*(PASS|FAIL)", re.IGNORECASE)

def parse_review(text):
    if not text:
        return "unparsed", ""
    m = REVIEW_VERDICT.search(text)
    if not m:
        return "unparsed", text.strip()[-1200:]
    if m.group(1).lower() == "pass":
        return "pass", ""
    return "fail", text[m.end():].strip()[:3000]

_PATH_RE = re.compile(r"(?:content|background|lib|popup|assets)/[\w./-]+\.\w+")

def escalation_block(repo, errors, target):
    """On a stalled fix round, append the CURRENT contents of the target file so
    the model edits from reality, not memory."""
    body = (repo / target).read_text(encoding="utf-8", errors="replace") \
        if (repo / target).exists() else "(file does not exist yet)"
    if len(body) > FILE_BUDGET:
        body = body[:FILE_BUDGET] + "\n... [truncated] ..."
    return (f"\nThe previous fix changed nothing. CURRENT contents of {target} — "
            f"edit this directly:\n\n----- {target} -----\n{body}\n")


# --- run state ------------------------------------------------------------
def now_iso():
    return datetime.datetime.now().isoformat(timespec="seconds")

def write_state(state):
    (REPO / "run_state.json").write_text(json.dumps(state, indent=2))

def write_report(state):
    lines = ["# Reel Blocker — orchestrator run report", "",
             f"Started: {state['started']}",
             f"Ended:   {state.get('ended', '(in progress)')}",
             f"Model: {state.get('model','(unset)')}", "",
             "| # | File | Status | Tries | Fixes | Review | Mins |",
             "|--:|:-----|:-------|:-----:|:-----:|:-------|----:|"]
    for s in state["stages"]:
        lines.append(f"| {s['n']} | {s['file']} | {s['status']} | "
                     f"{s.get('stage_attempts',0)} | {s.get('fix_rounds',0)} | "
                     f"{s.get('review','-')} | {round(s.get('duration_sec',0)/60,1)} |")
    failed = [s for s in state["stages"] if s["status"] not in ("verified", "skipped")]
    if failed:
        lines += ["", "## Needs attention"]
        for s in failed:
            lines.append(f"- #{s['n']} {s['file']}: {s['status']}"
                         + (f" — {s['error']}" if s.get("error") else ""))
        lines += ["", f"Resume with: `python3 orchestrator.py --from-stage={failed[0]['n']}`"]
    else:
        lines += ["", "All files verified. Review AGENT_SUMMARY.md, then load "
                  "unpacked and hand-test 'What Must Never Break'."]
    (REPO / "run_report.md").write_text("\n".join(lines) + "\n")


# --- one stage attempt ----------------------------------------------------
def attempt_stage(stage, baseline, log, do_review, deadline):
    """Primary build (model or scripted) + scope guard + fix/verify/review loop for
    a single file. Returns (passed, info)."""
    target = stage["file"]
    allowed = set(stage.get("allow") or []) | {target}
    expects = stage.get("expects") or [target]

    if stage.get("scripted"):
        run_scripted(REPO, stage["scripted"])
        scope_guard(REPO, baseline, expects)  # allow the generated files
        ok_v, vout = run_verify(REPO)
        print(vout, end=""); log.write(vout); log.flush()
        ok_c, cout = completeness(REPO, expects)
        if not ok_c:
            print(cout + "\n"); log.write(cout + "\n")
        return (ok_v and ok_c), dict(fix_rounds=0, review="scripted")

    primary = STYLE + ONE_FILE_PROMPT.format(file=target, spec=stage["spec"])
    run_claude(primary, MAX_TURNS, log, PRIMARY_TIMEOUT)
    scope_guard(REPO, baseline, allowed)

    last_sig = None
    review_rounds = fix_rounds = 0
    for rnd in range(1, MAX_FIX_ROUNDS + 1):
        if deadline and time.time() > deadline:
            return False, dict(reason="deadline", fix_rounds=fix_rounds, review="-")
        strip_module_syntax(REPO)
        ok_v, vout = run_verify(REPO)
        print(vout, end=""); log.write(vout); log.flush()
        ok_c, cout = completeness(REPO, expects)
        if not ok_c:
            print(cout + "\n"); log.write(cout + "\n")

        if ok_v and ok_c:
            if not (do_review and stage.get("review")):
                return True, dict(fix_rounds=fix_rounds, review="-")
            if review_rounds >= MAX_REVIEW_ROUNDS:
                return True, dict(fix_rounds=fix_rounds, review="exhausted")
            review_rounds += 1
            diff = stage_diff(REPO, baseline)
            rp = REVIEW_PROMPT.format(file=target, checklist=stage["review"], diff=diff)
            log.write(f"\n--- REVIEW {review_rounds} {target} ---\n")
            _, rtext = run_claude(rp, MAX_REVIEW_TURNS, log, REVIEW_TIMEOUT, capture=True)
            verdict, findings = parse_review(rtext)
            print(f"  [review {review_rounds}] {verdict}")
            if verdict in ("pass", "unparsed"):
                return True, dict(fix_rounds=fix_rounds, review=verdict)
            fix_rounds += 1
            fp = STYLE + REVIEW_FIX_PROMPT.format(file=target, findings=findings)
            run_claude(fp, MAX_FIX_TURNS, log, FIX_TIMEOUT)
            scope_guard(REPO, baseline, allowed)
            continue

        if rnd == MAX_FIX_ROUNDS:
            break
        errors = (vout + ("\n" + cout if not ok_c else "")).strip()
        sig = worktree_signature(REPO, baseline)
        escalate = (sig == last_sig)
        last_sig = sig
        esc = escalation_block(REPO, errors, target) if escalate else ""
        if escalate:
            print(f"  [escalate] round {rnd}: no change since last fix — injecting "
                  f"{target}")
        fix_rounds += 1
        fp = STYLE + FIX_PROMPT.format(file=target, errors=errors, escalation=esc)
        print(f"  [fix {rnd}/{MAX_FIX_ROUNDS}] feeding errors back...")
        log.write(f"\n--- FIX {rnd} {target} ---\n")
        run_claude(fp, MAX_FIX_TURNS, log, FIX_TIMEOUT)
        scope_guard(REPO, baseline, allowed)

    return False, dict(reason="fix-rounds-exhausted", fix_rounds=fix_rounds, review="-")


# --- preflight ------------------------------------------------------------
def preflight():
    problems = []
    if not shutil.which("claude"):
        problems.append("`claude` CLI not on PATH.")
    base = os.environ.get("ANTHROPIC_BASE_URL")
    if not base: problems.append("ANTHROPIC_BASE_URL is not set.")
    if not os.environ.get("ANTHROPIC_MODEL"): problems.append("ANTHROPIC_MODEL is not set.")
    if not os.environ.get("ANTHROPIC_API_KEY"):
        problems.append("ANTHROPIC_API_KEY is not set (proxies accept a dummy value, "
                        "but the CLI expects it present).")
    if base:
        url = base.rstrip("/") + "/v1/models"
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                if resp.status >= 400:
                    problems.append(f"Model server HTTP {resp.status} at {url}.")
        except Exception as e:
            problems.append(f"Model server not reachable at {url} ({e}).")
    return problems


# --- main -----------------------------------------------------------------
def main():
    dry       = "--dry-run" in sys.argv
    do_review = "--no-review" not in sys.argv
    skip_pre  = "--skip-preflight" in sys.argv
    start = None
    for a in sys.argv:
        if a.startswith("--from-stage="):
            start = int(a.split("=", 1)[1])

    subprocess.run(["chmod", "+x", "scripts/verify.sh"], cwd=REPO)
    if not (REPO / ".git").exists() and not dry:
        git(REPO, "init", check=True); git(REPO, "add", "-A")
        git(REPO, "commit", "-m", "chore: scaffold + harness")

    if start is None:
        start = (highest_stage_tag(REPO) + 1) if not dry else 1
        if start > 1:
            print(f"[resume] auto-resuming at stage {start} (found tag "
                  f"stage-{start-1}). Use --from-stage=1 to rebuild from scratch.")

    if dry:
        for i, stage in enumerate(FILES, 1):
            if i < start: continue
            tag = " [scripted]" if stage.get("scripted") else ""
            print(f"=== Stage {i}: {stage['file']}{tag} — {stage['desc']} ===")
        return

    if not skip_pre:
        problems = preflight()
        if problems:
            print("Preflight failed:")
            for p in problems: print("  - " + p)
            print("Fix the above, or rerun with --skip-preflight.")
            sys.exit(1)
        print("[preflight] environment OK.")

    deadline = (time.time() + RUN_HOURS * 3600) if RUN_HOURS > 0 else None
    state = dict(started=now_iso(),
                 model=os.environ.get("ANTHROPIC_MODEL", "(unset)"), stages=[])
    log = open(REPO / "build.log", "a")
    rec = None

    def finalize(msg=None):
        state.setdefault("ended", now_iso())
        write_state(state); write_report(state)
        try: log.close()
        except Exception: pass
        if msg: print(msg)

    try:
        for i, stage in enumerate(FILES, 1):
            rec = dict(n=i, file=stage["file"], status="pending", stage_attempts=0,
                       fix_rounds=0, review="-", duration_sec=0, commit=None, error=None)
            if i < start:
                rec["status"] = "skipped"; state["stages"].append(rec)
                write_state(state); continue
            if deadline and time.time() > deadline:
                rec["status"] = "not-reached"; rec["error"] = "deadline"
                state["stages"].append(rec)
                finalize(f"*** Deadline before stage {i}. Stopping. ***"); return

            state["stages"].append(rec)
            print(f"\n=== Stage {i}/{len(FILES)}: {stage['file']} — {stage['desc']} ===")
            t0 = time.time()
            baseline = head(REPO)

            passed, info = False, {}
            for attempt in range(1, MAX_STAGE_ATTEMPTS + 1):
                rec["stage_attempts"] = attempt
                if attempt > 1:
                    print(f"  [clean-slate] attempt {attempt}: re-running fresh")
                    log.write(f"\n--- CLEAN-SLATE {attempt} stage {i} ---\n")
                reset_clean(REPO, baseline)
                passed, info = attempt_stage(stage, baseline, log, do_review, deadline)
                rec["fix_rounds"] += info.get("fix_rounds", 0)
                rec["review"] = info.get("review", rec["review"])
                write_state(state)
                if passed or info.get("reason") == "deadline":
                    break

            rec["duration_sec"] = round(time.time() - t0, 1)
            if not passed:
                reason = info.get("reason", "unknown")
                reset_clean(REPO, baseline)
                rec["status"] = "failed"; rec["error"] = reason
                finalize(f"\n*** STOPPED at stage {i} ({stage['file']}): {reason}. "
                         f"Repo at last good commit. Resume with --from-stage={i}. ***")
                sys.exit(0 if reason == "deadline" else 1)

            git(REPO, "add", "-A")
            git(REPO, "-c", "user.email=erdy_gho@yahoo.com", "-c", "user.name=Erdy",
                "commit", "-q", "-m", f"build: {stage['file']} (stage {i}) verified")
            git(REPO, "tag", "-f", f"stage-{i}")
            rec["commit"] = head(REPO); rec["status"] = "verified"
            write_state(state); write_report(state)
            print(f"--- Stage {i} ({stage['file']}) verified + tagged stage-{i} "
                  f"({rec['duration_sec']/60:.1f} min). ---")

    except KeyboardInterrupt:
        if rec and rec["status"] == "pending":
            rec["status"] = "interrupted"; rec["error"] = "Ctrl+C"
        finalize("\n*** Interrupted (Ctrl+C). Last verified file is committed + "
                 "tagged; re-run with no args to auto-resume. ***"); return
    except AbortRun as e:
        if rec and rec["status"] == "pending":
            rec["status"] = "aborted"; rec["error"] = str(e)
        finalize(f"\n*** ABORTED: {e} Fix the server and re-run to auto-resume. ***")
        sys.exit(1)

    finalize("\nDone. See run_report.md and AGENT_SUMMARY.md. Load unpacked and "
             "hand-test 'What Must Never Break'.")


if __name__ == "__main__":
    main()
